// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/hltl/GoMall/biz/handler"
	router "github.com/hltl/GoMall/biz/router"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.GET("/debug", router.UserHandlerRegister)

	// your code ...
}

func Register(r *server.Hertz) {
	r.POST("/register", router.UserHandlerRegister)
	r.POST("/login", router.UserHandlerLogin)
}
