// Code generated by hertz generator. DO NOT EDIT.

package main

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hltl/GoMall/biz/router"
)

// register registers all routers.
func register(r *server.Hertz, authClient *router.AuthClient) {
	// 示例路由
	r.GET("/api/token", func(c context.Context, ctx *app.RequestContext) {
		// 使用authClient生成token
		token, err := authClient.DeliverToken(123)
		if err != nil {
			ctx.JSON(500, map[string]string{"error": err.Error()})
			return
		}
		ctx.JSON(200, map[string]string{"token": token})
	})

	// 只保留统一的注册入口
	router.Register(r)

	customizedRegister(r)
}
